#!/usr/bin/env bash
# Combine <out-dir>/before/report.json and <out-dir>/after/report.json into
# <out-dir>/REPORT.md and print the overall verdict. Exit 0 only for FIX VERIFIED
# unless --no-fail is passed.
#
# Usage: scripts/compose-report.sh <out-dir> [--pr-json <resolve-pr output>] [--no-fail]
set -euo pipefail

OUT=""; PR_JSON=""; NO_FAIL=0
while [ $# -gt 0 ]; do
  case "$1" in
    --pr-json) PR_JSON="$2"; shift 2 ;;
    --no-fail) NO_FAIL=1; shift ;;
    *) OUT="$1"; shift ;;
  esac
done
[ -n "$OUT" ] || { sed -n '2,6p' "$0" >&2; exit 2; }

B="$OUT/before/report.json"; A="$OUT/after/report.json"
for f in "$B" "$A"; do [ -f "$f" ] || { echo "error: missing $f" >&2; exit 2; }; done

bv=$(jq -r .verdict "$B"); av=$(jq -r .verdict "$A")
case "$bv/$av" in
  bug_present/bug_absent) VERDICT="FIX VERIFIED"; ICON="✅" ;;
  bug_present/bug_present) VERDICT="NOT FIXED"; ICON="❌" ;;
  bug_absent/*) VERDICT="BUG NOT REPRODUCED BEFORE"; ICON="⚠️" ;;
  *) VERDICT="INCONCLUSIVE"; ICON="⚠️" ;;
esac

title="Pull request verification"; prline=""
if [ -n "$PR_JSON" ] && [ -f "$PR_JSON" ]; then
  title=$(jq -r '"\(.repo)#\(.number): \(.title)"' "$PR_JSON")
  prline=$(jq -r '"PR: \(.url)  \nIssue(s): \([.issues[].url] | join(", "))  \nbefore = `\(.before[:10])`, after = `\(.after[:10])`"' "$PR_JSON")
fi

cell() { # $1 = report.json, $2 = jq path; markdown-table-safe scalar
  jq -r "$2"' // "" | tostring | gsub("\\|"; "\\|") | gsub("\r?\n"; " ")' "$1"
}

steps_table() { # $1 = report.json
  jq -r '.steps[] | "| \(.n) | \(.action // "" | tostring | gsub("\\|"; "\\|") | gsub("\r?\n"; " ")) | \(.observed // "" | tostring | gsub("\\|"; "\\|") | gsub("\r?\n"; " ")) | \(if .screenshot then "![step \(.n)](\(.screenshot))" else "" end) |"' "$1"
}

{
  echo "# $ICON $VERDICT — $title"
  echo
  [ -n "$prline" ] && { echo "$prline"; echo; }
  echo "| | before | after |"
  echo "|---|---|---|"
  echo "| verdict | \`$bv\` | \`$av\` |"
  echo "| confidence | $(jq -r .confidence "$B") | $(jq -r .confidence "$A") |"
  echo "| commit | \`$(jq -r '.sha[:10]' "$B")\` | \`$(jq -r '.sha[:10]' "$A")\` |"
  echo "| summary | $(cell "$B" .summary) | $(cell "$A" .summary) |"
  echo "| recording | [$(jq -r .evidence.recording "$B")]($(jq -r .evidence.recording "$B")) | [$(jq -r .evidence.recording "$A")]($(jq -r .evidence.recording "$A")) |"
  echo
  for s in before after; do
    f="$OUT/$s/report.json"
    echo "## ${s} — $(jq -r .verdict "$f")"
    echo
    echo "| # | action | observed | screenshot |"
    echo "|---|---|---|---|"
    steps_table "$f"
    echo
  done
  echo "_Generated by argent-pr-verify on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
} > "$OUT/REPORT.md"

jq -n --arg v "$VERDICT" --arg b "$bv" --arg a "$av" '{verdict:$v, before:$b, after:$a}' > "$OUT/verdict.json"
echo "$VERDICT (before=$bv, after=$av) -> $OUT/REPORT.md"
[ "$VERDICT" = "FIX VERIFIED" ] || [ "$NO_FAIL" = 1 ]
